//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace company.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int ProductId { get; set; }
        public int OrderId { get; set; }
        public int OrderDetailsId { get; set; }
        public int Quentity { get; set; }
        public string Size { get; set; }
        public int ColorId { get; set; }
    }
}
